services:
  mongodb:
    image: mongo:6.0
    container_name: taskmanager-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=taskdb

  postgres:
    image: postgres:15-alpine
    container_name: taskdb-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres